import Link from "next/link";
import {ArrowIcon,BoxIcon,ChartIcon,ClockIcon,HomeIcon,LockIcon,PaletteIcon,ShieldIcon,StarIcon,UsersIcon} from "@/components/icons";
import {LandingHeader} from "@/components/landing-header";
const features=[[HomeIcon,"Display home management","Upload rooms, tag products, manage opening hours and visitor data in one place."],[UsersIcon,"Lead capture & CRM","Capture visitor interest automatically. Push qualified leads to your CRM with zero manual entry."],[PaletteIcon,"Colour selection exports","Let customers save selections and export them as PDFs, ready for consultant review."]] as const;
const benefits=[[ShieldIcon,"Built for the industry","Designed specifically for display homes, builders and suppliers."],[LockIcon,"Secure & reliable","Enterprise-grade security and Australian-based support."],[ClockIcon,"Save time","Automate admin and focus on what matters most."],[ChartIcon,"Drive more sales","Connect the right products with the right buyers."]] as const;
export default function Home(){
 return <main><section className="hero"><LandingHeader/>
 <div className="hero-content container"><div className="eyebrow"><StarIcon size={15}/> Australia&apos;s leading display home platform</div><h1>Connect display homes<br/>with the <em>right</em> buyers</h1><p>A single platform where builders showcase display homes,<br/>suppliers feature products, and buyers discover both.</p><div className="hero-actions"><Link className="button button-cream" href="/builder/register"><HomeIcon/> Register as a builder <ArrowIcon size={18}/></Link><Link className="button button-outline" href="/supplier"><BoxIcon/> Register as a supplier <ArrowIcon size={18}/></Link></div><a className="scroll-cue" href="#how-it-works"><span>↓</span>Scroll to explore</a></div></section>
 <section className="feature-strip" id="how-it-works"><div className="container feature-grid">{features.map(([Icon,title,text])=><article className="feature-card" key={title}><div className="icon-circle"><Icon/></div><div><h2>{title}</h2><p>{text}</p><ArrowIcon size={18}/></div></article>)}</div></section>
 <section className="audiences"><article className="audience-card builders" id="for-builders"><div className="audience-content"><div className="glass-icon"><HomeIcon size={31}/></div><h2>For builders</h2><span className="audience-divider"/><p>Showcase your display homes,<br/>capture leads and give customers<br/>a seamless selection experience.</p><Link className="audience-link" href="/builder/register">Get started as a builder <ArrowIcon size={18}/></Link></div></article><article className="audience-card suppliers" id="for-suppliers"><div className="audience-content"><div className="glass-icon"><BoxIcon size={31}/></div><h2>For suppliers</h2><span className="audience-divider"/><p>Feature your products inside<br/>display homes and reach buyers<br/>at the perfect moment.</p><Link className="audience-link" href="/supplier">Get started as a supplier <ArrowIcon size={18}/></Link></div></article></section>
 <section className="trusted"><p>Trusted by leading builders and suppliers across Australia</p><div className="container trusted-logos"><strong>metricon</strong><strong>MASTERTON</strong><strong>Clarendon<br/>Homes</strong><strong>Henley<br/>Homes</strong><strong>mcdonald jones</strong><strong>BSD</strong></div></section>
 <section className="benefits" id="pricing"><div className="container benefits-grid">{benefits.map(([Icon,title,text])=><article key={title}><Icon size={31}/><h2>{title}</h2><p>{text}</p></article>)}</div></section>
 <footer className="site-footer"><div className="container footer-inner"><div><span className="logo">wtf?</span><small>© 2026 WTF? All rights reserved.</small></div><nav><a href="#">About us</a><a href="#">Contact</a><a href="#">Privacy</a><a href="#">Terms</a></nav></div></footer></main>
}
