import { BookOpenIcon, CameraIcon, FileIcon, HomeIcon, PaletteIcon, SparklesIcon } from "@/components/icons";

export const createDisplayHomeSteps = [
  { id: "details", eyebrow: "Step 1", shortLabel: "1", title: "Details", description: "Add all the essential information about your display home.", icon: HomeIcon },
  { id: "classification", eyebrow: "Step 2", shortLabel: "2", title: "Classification", description: "Define how your display home should be categorised.", icon: SparklesIcon },
  { id: "floor-plan", eyebrow: "Step 3", shortLabel: "3", title: "Floor Plan Upload", description: "Upload your floor plan to get started.", icon: FileIcon },
  { id: "rooms", eyebrow: "Step 4", shortLabel: "4", title: "AI Detected Rooms", description: "Review, edit or add any missing rooms.", icon: BookOpenIcon },
  { id: "products-upload", eyebrow: "Step 5", shortLabel: "5", title: "Product Guide Upload", description: "Upload your products to get started.", icon: FileIcon },
  { id: "colour-review", eyebrow: "Step 6", shortLabel: "6", title: "AI Colour Combination Review", description: "Review compatible colour combinations generated from the product guide.", icon: PaletteIcon },
  { id: "products-result", eyebrow: "Step 7", shortLabel: "7", title: "Products Result", description: "AI extracted products", icon: BookOpenIcon },
  { id: "products-verify-edit", eyebrow: "Step 8", shortLabel: "8", title: "Products Verify", description: "Products Verify and Edit", icon: BookOpenIcon },
  { id: "qr", eyebrow: "Step 9", shortLabel: "9", title: "QR Generated", description: "Your display home is ready for visitors.", icon: CameraIcon },
] as const;

export type CreateDisplayHomeStepId = (typeof createDisplayHomeSteps)[number]["id"];

export const homeUploads = [
  { label: "Floor plan", note: "Upload PDF", icon: FileIcon },
  { label: "Brochure", note: "Upload PDF", icon: BookOpenIcon },
  { label: "Photography", note: "Upload images", icon: CameraIcon },
] as const;

export const targetMarkets = ["First home buyer", "Family", "Upsizer", "Investor"] as const;

export const detectedRooms = [
  { name: "Living room", products: "flooring, soft furnishings, lighting", icon: HomeIcon },
  { name: "Kitchen", products: "benchtops, cabinetry, tapware", icon: SparklesIcon },
  { name: "Ensuite", products: "tiles, tapware, vanity, mirrors", icon: BookOpenIcon },
] as const;

export const extractedProducts = [
  { name: "Calacatta Quartz 20mm", code: "CST-CQ-20", supplier: "Caesarstone", confidence: "0.93", status: "approved", image: "/builder_section.png" },
  { name: "Shaker Profile Cabinetry", code: "POL-SHP-W", supplier: "Polytec", confidence: "0.85", status: "pending", image: "/hero.png" },
  { name: "Unknown - ref #4482-B", code: "p13", supplier: "No supplier", confidence: "Low quality", status: "flagged", image: "/supplier_section.png" },
] as const;

export const colourReviewTabs = ["Exterior", "Kitchen", "Bathrooms", "Laundry", "Interior Finishes"] as const;

export const colourReviewCombinations = [
  {
    category: "Exterior",
    name: "Modern Dark",
    vibe: "Bold - Contemporary - Timeless",
    badge: "Recommended",
    upgrades: 4,
    image: "/hero.png",
    summary: "3 standard items and 4 upgrades",
    items: [
      { label: "Roofing", status: "Upgrade", value: "Colorbond Monument", tone: "upgrade" },
      { label: "Bricks", status: "Upgrade", value: "Elements Graphite", tone: "upgrade" },
      { label: "Cladding", status: "Standard", value: "Woodland Grey", tone: "standard" },
      { label: "Windows", status: "Upgrade", value: "Aluminium Frames Black", tone: "upgrade" },
      { label: "Garage Door", status: "Upgrade", value: "Colorbond Monument", tone: "upgrade" },
      { label: "Driveway", status: "Standard", value: "Charcoal", tone: "standard" },
      { label: "Entry Door", status: "Upgrade", value: "Thermoclad Monument", tone: "upgrade" },
    ],
    summaryStats: { standard: 3, upgrade: 4 },
  },
  {
    category: "Exterior",
    name: "Coastal Light",
    vibe: "Coastal - Fresh - Inviting",
    badge: "2 Upgrades",
    upgrades: 2,
    image: "/builder_section.png",
    summary: "5 standard items and 2 upgrades",
    items: [
      { label: "Roofing", status: "Standard", value: "Colorbond Surfmist", tone: "standard" },
      { label: "Bricks", status: "Standard", value: "Simply Hamptons Fresh White", tone: "standard" },
      { label: "Cladding", status: "Standard", value: "Surfmist", tone: "standard" },
      { label: "Windows", status: "Standard", value: "Aluminium Frames Surfmist", tone: "standard" },
      { label: "Garage Door", status: "Standard", value: "Surfmist", tone: "standard" },
      { label: "Driveway", status: "Upgrade", value: "Silver Sands", tone: "upgrade" },
      { label: "Entry Door", status: "Standard", value: "Thermoclad Surfmist", tone: "standard" },
    ],
    summaryStats: { standard: 5, upgrade: 2 },
  },
  {
    category: "Exterior",
    name: "Warm Natural",
    vibe: "Natural - Warm - Balanced",
    badge: "3 Upgrades",
    upgrades: 3,
    image: "/supplier_section.png",
    summary: "4 standard items and 3 upgrades",
    items: [
      { label: "Roofing", status: "Standard", value: "Colorbond Dune", tone: "standard" },
      { label: "Bricks", status: "Upgrade", value: "Elements Jarosite", tone: "upgrade" },
      { label: "Cladding", status: "Upgrade", value: "Ghost Gum", tone: "upgrade" },
      { label: "Windows", status: "Standard", value: "Aluminium Frames Paperbark", tone: "standard" },
      { label: "Garage Door", status: "Standard", value: "Dune", tone: "standard" },
      { label: "Driveway", status: "Upgrade", value: "Lite Mocha", tone: "upgrade" },
      { label: "Entry Door", status: "Upgrade", value: "Thermoclad Dune", tone: "upgrade" },
    ],
    summaryStats: { standard: 4, upgrade: 3 },
  },
  {
    category: "Exterior",
    name: "Urban Slate",
    vibe: "Sharp - Minimal - Refined",
    badge: "1 Upgrade",
    upgrades: 1,
    image: "/builder_section.png",
    summary: "6 standard items and 1 upgrade",
    items: [
      { label: "Roofing", status: "Standard", value: "Colorbond Monument", tone: "standard" },
      { label: "Bricks", status: "Standard", value: "Charcoal Smooth", tone: "standard" },
      { label: "Cladding", status: "Standard", value: "Basalt", tone: "standard" },
      { label: "Windows", status: "Standard", value: "Black Frames", tone: "standard" },
      { label: "Garage Door", status: "Upgrade", value: "Matte Black", tone: "upgrade" },
      { label: "Driveway", status: "Standard", value: "Slate", tone: "standard" },
      { label: "Entry Door", status: "Standard", value: "Monument", tone: "standard" },
    ],
    summaryStats: { standard: 6, upgrade: 1 },
  },
  {
    category: "Kitchen",
    name: "Warm Oak",
    vibe: "Soft - Natural - Bright",
    badge: "Recommended",
    upgrades: 2,
    image: "/hero.png",
    summary: "5 standard items and 2 upgrades",
    items: [
      { label: "Cabinetry", status: "Standard", value: "Natural Oak", tone: "standard" },
      { label: "Benchtop", status: "Upgrade", value: "Calacatta Quartz", tone: "upgrade" },
      { label: "Splashback", status: "Standard", value: "Warm White Tile", tone: "standard" },
      { label: "Tapware", status: "Standard", value: "Brushed Nickel", tone: "standard" },
      { label: "Handles", status: "Standard", value: "Champagne", tone: "standard" },
      { label: "Sink", status: "Upgrade", value: "Undermount Granite", tone: "upgrade" },
      { label: "Flooring", status: "Standard", value: "Light Timber", tone: "standard" },
    ],
    summaryStats: { standard: 5, upgrade: 2 },
  },
  {
    category: "Kitchen",
    name: "Deep Charcoal",
    vibe: "Moody - Contemporary - Luxe",
    badge: "2 Upgrades",
    upgrades: 2,
    image: "/supplier_section.png",
    summary: "4 standard items and 3 upgrades",
    items: [
      { label: "Cabinetry", status: "Upgrade", value: "Deep Grey", tone: "upgrade" },
      { label: "Benchtop", status: "Standard", value: "Concrete Mist", tone: "standard" },
      { label: "Splashback", status: "Upgrade", value: "Dark Vein Stone", tone: "upgrade" },
      { label: "Tapware", status: "Standard", value: "Black", tone: "standard" },
      { label: "Handles", status: "Standard", value: "Black", tone: "standard" },
      { label: "Sink", status: "Standard", value: "Gunmetal", tone: "standard" },
      { label: "Flooring", status: "Upgrade", value: "Smoked Timber", tone: "upgrade" },
    ],
    summaryStats: { standard: 4, upgrade: 3 },
  },
  {
    category: "Bathrooms",
    name: "Spa Calm",
    vibe: "Calm - Clean - Spa",
    badge: "Recommended",
    upgrades: 1,
    image: "/builder_section.png",
    summary: "6 standard items and 1 upgrade",
    items: [
      { label: "Tiles", status: "Standard", value: "Soft Sand", tone: "standard" },
      { label: "Vanity", status: "Standard", value: "Oak Laminate", tone: "standard" },
      { label: "Tapware", status: "Upgrade", value: "Brushed Brass", tone: "upgrade" },
      { label: "Shower Screen", status: "Standard", value: "Frameless Clear", tone: "standard" },
      { label: "Mirror", status: "Standard", value: "Slim Edge", tone: "standard" },
      { label: "Basin", status: "Standard", value: "Soft White", tone: "standard" },
      { label: "Grout", status: "Standard", value: "Warm Grey", tone: "standard" },
    ],
    summaryStats: { standard: 6, upgrade: 1 },
  },
  {
    category: "Laundry",
    name: "Clean Utility",
    vibe: "Practical - Bright - Streamlined",
    badge: "Recommended",
    upgrades: 1,
    image: "/builder_section.png",
    summary: "6 standard items and 1 upgrade",
    items: [
      { label: "Cabinetry", status: "Standard", value: "White Laminate", tone: "standard" },
      { label: "Benchtop", status: "Standard", value: "Compact Laminate", tone: "standard" },
      { label: "Splashback", status: "Upgrade", value: "Subway Tile", tone: "upgrade" },
      { label: "Tapware", status: "Standard", value: "Chrome", tone: "standard" },
      { label: "Handles", status: "Standard", value: "Chrome", tone: "standard" },
      { label: "Appliances", status: "Standard", value: "60cm Washer Dryer", tone: "standard" },
      { label: "Flooring", status: "Standard", value: "Porcelain Tile", tone: "standard" },
    ],
    summaryStats: { standard: 6, upgrade: 1 },
  },
  {
    category: "Interior Finishes",
    name: "Textured Linen",
    vibe: "Warm - Relaxed - Layered",
    badge: "Recommended",
    upgrades: 2,
    image: "/hero.png",
    summary: "5 standard items and 2 upgrades",
    items: [
      { label: "Wall Colour", status: "Standard", value: "Linen White", tone: "standard" },
      { label: "Skirting", status: "Standard", value: "Warm White", tone: "standard" },
      { label: "Doors", status: "Upgrade", value: "Natural Timber", tone: "upgrade" },
      { label: "Hardware", status: "Standard", value: "Brushed Nickel", tone: "standard" },
      { label: "Feature Wall", status: "Upgrade", value: "Textured Clay", tone: "upgrade" },
      { label: "Ceiling", status: "Standard", value: "White", tone: "standard" },
      { label: "Architraves", status: "Standard", value: "Warm White", tone: "standard" },
    ],
    summaryStats: { standard: 5, upgrade: 2 },
  },
] as const;

export const selectedColourReviewCombination = {
  label: "Modern Dark",
  image: "/hero.png",
  theme: "Modern Dark",
  items: [
    { label: "Roofing", status: "Upgrade", value: "Colorbond Monument", tone: "upgrade" },
    { label: "Bricks", status: "Upgrade", value: "Elements Graphite", tone: "upgrade" },
    { label: "Cladding", status: "Standard", value: "Woodland Grey", tone: "standard" },
    { label: "Windows", status: "Upgrade", value: "Aluminium Frames Black", tone: "upgrade" },
    { label: "Garage Door", status: "Upgrade", value: "Colorbond Monument", tone: "upgrade" },
    { label: "Driveway", status: "Standard", value: "Charcoal", tone: "standard" },
    { label: "Entry Door", status: "Upgrade", value: "Thermoclad Monument", tone: "upgrade" },
  ],
  summaryStats: { standard: 3, upgrade: 4 },
} as const;
